import type { AppState } from './state';
import { EXPIRY_WARNING_DAYS } from './types';
import { isoDate, isoTimestamp, money } from './money';

/** Dates are generated relative to today so every state is always live. */
const today = new Date();
function inDays(days: number): string {
  return isoDate(new Date(today.getTime() + days * 86_400_000));
}
function hoursAgo(hours: number): string {
  return isoTimestamp(new Date(today.getTime() - hours * 3_600_000));
}

/* ------------------------------------------------------------------ people */

const owner = {
  id: 'usr-owner',
  name: 'Khadija Bello',
  email: 'khadija@pharmaflow.ng',
  role: 'owner' as const,
  phone: '+2348030000001',
  licenseNumber: 'PCN/NG/22341',
  canApprovePricing: true,
};

const assistant = {
  id: 'usr-assistant',
  name: 'Aisha Yusuf',
  email: 'aisha@pharmaflow.ng',
  role: 'assistant' as const,
  phone: '+2348030000002',
  canApprovePricing: false,
};

export const SEED_USERS: AppState['users'] = [owner, assistant];

/* -------------------------------------------------------------- medicines */

/**
 * Fourteen products chosen to cover every state the UI has to render: healthy,
 * low, out, expiring, expired, safety-locked, recalled batch, controlled,
 * brand-with-generic, thin margin, high velocity, and overstocked.
 *
 * v2 shipped 50+ near-identical demo products; these cover more states in a
 * fifth of the lines, and every screen is forced to handle the awkward cases.
 */
export const SEED_MEDICINES: AppState['medicines'] = [
  {
    id: 'med-paracetamol',
    barcode: '8901030365012',
    name: 'Paracetamol Tablets',
    genericName: 'Paracetamol',
    strength: '500mg',
    dosageForm: 'Tablet',
    category: 'Analgesic',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 200 },
      { key: 'card', name: 'Card (10)', multiplier: 10, sellingPrice: 2000 },
      { key: 'box', name: 'Box (100)', multiplier: 100, sellingPrice: 20000 },
    ],
    totalQuantity: 480,
    lowStockThreshold: 150,
    expiryDate: inDays(400),
    supplier: 'sup-abc',
    purchaseDate: inDays(-40),
    costPerBaseUnit: 100,
    pricePerBaseUnit: 200,
    batches: [
      {
        id: 'bat-para-1',
        batchNumber: 'BN-EMZ-2604A',
        expiryDate: inDays(400),
        quantity: 300,
        costPerBaseUnit: 100,
        supplier: 'sup-abc',
        receivedDate: inDays(-40),
        isRecalled: false,
      },
      {
        id: 'bat-para-2',
        batchNumber: 'BN-EMZ-2605B',
        expiryDate: inDays(280),
        quantity: 180,
        costPerBaseUnit: 105,
        supplier: 'sup-abc',
        receivedDate: inDays(-20),
        isRecalled: false,
      },
    ],
    commonUse: 'Fever, headache and mild pain relief.',
    storage: 'Store below 25°C in a dry place, away from direct sunlight.',
    prescriptionStatus: 'OTC',
    warnings: ['Do not exceed 8 tablets in 24 hours.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-04-1224',
    manufacturer: 'Emzor Pharmaceutical',
    averageDailySales: 24,
  },
  {
    id: 'med-amoxicillin',
    barcode: '8901030990018',
    name: 'Amoxicillin Capsules',
    genericName: 'Amoxicillin',
    strength: '500mg',
    dosageForm: 'Capsule',
    category: 'Antibiotic',
    units: [
      { key: 'capsule', name: 'Capsule', multiplier: 1, sellingPrice: 350 },
      { key: 'pack', name: 'Pack (21)', multiplier: 21, sellingPrice: 7000 },
    ],
    totalQuantity: 84,
    lowStockThreshold: 100,
    expiryDate: inDays(310),
    supplier: 'sup-medplus',
    purchaseDate: inDays(-55),
    costPerBaseUnit: 160,
    pricePerBaseUnit: 350,
    batches: [
      {
        id: 'bat-amox-1',
        batchNumber: 'BN-AMP-2512C',
        expiryDate: inDays(310),
        quantity: 84,
        costPerBaseUnit: 160,
        supplier: 'sup-medplus',
        receivedDate: inDays(-55),
        isRecalled: false,
      },
    ],
    commonUse: 'Bacterial infections of the ear, nose, throat, skin and urinary tract.',
    storage: 'Store below 25°C, protected from moisture.',
    prescriptionStatus: 'Prescription',
    warnings: [
      'Complete the full course even if symptoms improve.',
      'Not suitable for patients allergic to penicillin.',
    ],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-02-9910',
    manufacturer: 'Might Healthcare',
    averageDailySales: 11,
  },
  {
    id: 'med-coartem',
    barcode: '8901030455123',
    name: 'Coartem Tablets',
    genericName: 'Artemether / Lumefantrine',
    strength: '80mg / 480mg',
    dosageForm: 'Tablet',
    category: 'Antimalarial',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 450 },
      { key: 'course', name: 'Course (6)', multiplier: 6, sellingPrice: 2700 },
    ],
    totalQuantity: 360,
    lowStockThreshold: 120,
    expiryDate: inDays(520),
    supplier: 'sup-abc',
    purchaseDate: inDays(-30),
    costPerBaseUnit: 260,
    pricePerBaseUnit: 450,
    batches: [
      {
        id: 'bat-coa-1',
        batchNumber: 'BN-COA-2603A',
        expiryDate: inDays(520),
        quantity: 360,
        costPerBaseUnit: 260,
        supplier: 'sup-abc',
        receivedDate: inDays(-30),
        isRecalled: false,
      },
    ],
    commonUse: 'Uncomplicated P. falciparum malaria in adults and children.',
    storage: 'Store below 30°C, protected from light.',
    prescriptionStatus: 'OTC',
    warnings: ['Take with food to aid absorption.'],
    isBrand: true,
    genericEquivalentId: 'med-artemether',
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-03-4471',
    manufacturer: 'Novartis Nigeria',
    averageDailySales: 18,
  },
  {
    id: 'med-artemether',
    barcode: '8901030455130',
    name: 'Artemether Tablets',
    genericName: 'Artemether / Lumefantrine',
    strength: '80mg / 480mg',
    dosageForm: 'Tablet',
    category: 'Antimalarial',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 320 },
      { key: 'course', name: 'Course (6)', multiplier: 6, sellingPrice: 1920 },
    ],
    totalQuantity: 96,
    lowStockThreshold: 100,
    expiryDate: inDays(190),
    supplier: 'sup-medplus',
    purchaseDate: inDays(-25),
    costPerBaseUnit: 170,
    pricePerBaseUnit: 320,
    batches: [
      {
        id: 'bat-art-1',
        batchNumber: 'BN-ART-2604B',
        expiryDate: inDays(190),
        quantity: 96,
        costPerBaseUnit: 170,
        supplier: 'sup-medplus',
        receivedDate: inDays(-25),
        isRecalled: false,
      },
    ],
    commonUse: 'Generic alternative for uncomplicated malaria.',
    storage: 'Store below 30°C, protected from light.',
    prescriptionStatus: 'OTC',
    warnings: ['Take with food to aid absorption.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-03-8812',
    manufacturer: 'Greenfield Pharmaceuticals',
    averageDailySales: 6,
  },
  {
    id: 'med-omeprazole',
    barcode: '8901030777004',
    name: 'Omeprazole Capsules',
    genericName: 'Omeprazole',
    strength: '20mg',
    dosageForm: 'Capsule',
    category: 'Antacid',
    units: [
      { key: 'capsule', name: 'Capsule', multiplier: 1, sellingPrice: 180 },
      { key: 'strip', name: 'Strip (14)', multiplier: 14, sellingPrice: 2400 },
    ],
    totalQuantity: 210,
    lowStockThreshold: 80,
    // Expiring inside the warning window.
    expiryDate: inDays(EXPIRY_WARNING_DAYS - 30),
    supplier: 'sup-abc',
    purchaseDate: inDays(-120),
    costPerBaseUnit: 70,
    pricePerBaseUnit: 180,
    batches: [
      {
        id: 'bat-omp-1',
        batchNumber: 'BN-OMP-2508A',
        expiryDate: inDays(EXPIRY_WARNING_DAYS - 30),
        quantity: 210,
        costPerBaseUnit: 70,
        supplier: 'sup-abc',
        receivedDate: inDays(-120),
        isRecalled: false,
      },
    ],
    commonUse: 'Acid reflux, heartburn and stomach ulcer management.',
    storage: 'Store below 25°C in the original blister packaging.',
    prescriptionStatus: 'OTC',
    warnings: ['Swallow whole — do not crush or chew.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-01-3345',
    manufacturer: 'Macleods Nigeria',
    averageDailySales: 9,
  },
  {
    id: 'med-tramadol',
    barcode: '8901030666012',
    name: 'Tramadol Capsules',
    genericName: 'Tramadol HCl',
    strength: '50mg',
    dosageForm: 'Capsule',
    category: 'Analgesic',
    units: [
      { key: 'capsule', name: 'Capsule', multiplier: 1, sellingPrice: 480 },
      { key: 'strip', name: 'Strip (10)', multiplier: 10, sellingPrice: 4600 },
    ],
    totalQuantity: 60,
    lowStockThreshold: 40,
    expiryDate: inDays(260),
    supplier: 'sup-medplus',
    purchaseDate: inDays(-60),
    costPerBaseUnit: 210,
    pricePerBaseUnit: 480,
    batches: [
      {
        id: 'bat-tra-1',
        batchNumber: 'BN-TRA-2601A',
        expiryDate: inDays(260),
        quantity: 60,
        costPerBaseUnit: 210,
        supplier: 'sup-medplus',
        receivedDate: inDays(-60),
        isRecalled: false,
      },
    ],
    commonUse: 'Moderate to severe pain that requires an opioid.',
    storage: 'Store below 30°C, protected from light.',
    prescriptionStatus: 'Controlled',
    warnings: [
      'Schedule II — record the prescriber on every sale.',
      'May cause drowsiness. Do not drive after taking.',
      'Risk of dependence with prolonged use.',
    ],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-04-7712',
    manufacturer: 'Sun Pharma Nigeria',
    averageDailySales: 3,
  },
  {
    id: 'med-metronidazole',
    barcode: '8901030888015',
    name: 'Metronidazole Tablets',
    genericName: 'Metronidazole',
    strength: '500mg',
    dosageForm: 'Tablet',
    category: 'Antibiotic',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 140 },
      { key: 'strip', name: 'Strip (10)', multiplier: 10, sellingPrice: 1350 },
    ],
    totalQuantity: 75,
    lowStockThreshold: 40,
    // Already past date — must be blocked from sale.
    expiryDate: inDays(-12),
    supplier: 'sup-abc',
    purchaseDate: inDays(-180),
    costPerBaseUnit: 45,
    pricePerBaseUnit: 140,
    batches: [
      {
        id: 'bat-met-1',
        batchNumber: 'BN-MET-2502A',
        expiryDate: inDays(-12),
        quantity: 75,
        costPerBaseUnit: 45,
        supplier: 'sup-abc',
        receivedDate: inDays(-180),
        isRecalled: false,
      },
    ],
    commonUse: 'Bacterial vaginosis, amoebiasis and some skin infections.',
    storage: 'Store below 25°C, protected from light.',
    prescriptionStatus: 'Prescription',
    warnings: ['Avoid alcohol during and for 48 hours after the course.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-01-2298',
    manufacturer: 'Emzor Pharmaceutical',
    averageDailySales: 4,
  },
  {
    id: 'med-ciprofloxacin',
    barcode: '8901030999008',
    name: 'Ciprofloxacin Tablets',
    genericName: 'Ciprofloxacin',
    strength: '500mg',
    dosageForm: 'Tablet',
    category: 'Antibiotic',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 620 },
      { key: 'strip', name: 'Strip (10)', multiplier: 10, sellingPrice: 6000 },
    ],
    // Out of stock, high velocity — the reorder engine should shout about this.
    totalQuantity: 0,
    lowStockThreshold: 60,
    expiryDate: inDays(300),
    supplier: 'sup-medplus',
    purchaseDate: inDays(-70),
    costPerBaseUnit: 340,
    pricePerBaseUnit: 620,
    batches: [],
    commonUse: 'Urinary tract and gastrointestinal bacterial infections.',
    storage: 'Store below 25°C, away from light.',
    prescriptionStatus: 'Prescription',
    warnings: ['Avoid dairy and antacids within 2 hours of each dose.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-02-5510',
    manufacturer: 'FIDSON Healthcare',
    averageDailySales: 8,
  },
  {
    id: 'med-cough-syrup',
    barcode: '8901030111006',
    name: 'Cough Syrup',
    genericName: 'Dextromethorphan',
    strength: '100mg / 5ml',
    dosageForm: 'Syrup',
    category: 'Cold & Flu',
    units: [
      { key: 'bottle', name: 'Bottle (100ml)', multiplier: 1, sellingPrice: 2400 },
    ],
    totalQuantity: 22,
    lowStockThreshold: 15,
    expiryDate: inDays(150),
    supplier: 'sup-abc',
    purchaseDate: inDays(-45),
    // Thin margin on purpose: this is what the Pricing screen is for.
    costPerBaseUnit: 2050,
    pricePerBaseUnit: 2400,
    batches: [
      {
        id: 'bat-cou-1',
        batchNumber: 'BN-CGH-2604C',
        expiryDate: inDays(150),
        quantity: 22,
        costPerBaseUnit: 2050,
        supplier: 'sup-abc',
        receivedDate: inDays(-45),
        isRecalled: false,
      },
    ],
    commonUse: 'Dry cough relief in adults and children over 12.',
    storage: 'Store below 25°C. Once opened, use within 14 days.',
    prescriptionStatus: 'OTC',
    warnings: ['Do not use with MAO inhibitors.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-05-6612',
    manufacturer: 'Crompton Healthcare',
    averageDailySales: 2,
  },
  {
    id: 'med-vitamin-c',
    barcode: '8901030222002',
    name: 'Vitamin C Tablets',
    genericName: 'Ascorbic Acid',
    strength: '100mg',
    dosageForm: 'Tablet',
    category: 'Supplement',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 60 },
      { key: 'bottle', name: 'Bottle (100)', multiplier: 100, sellingPrice: 5500 },
    ],
    // Overstocked: 1200 units against ~1/day.
    totalQuantity: 1200,
    lowStockThreshold: 100,
    expiryDate: inDays(610),
    supplier: 'sup-abc',
    purchaseDate: inDays(-90),
    costPerBaseUnit: 18,
    pricePerBaseUnit: 60,
    batches: [
      {
        id: 'bat-vit-1',
        batchNumber: 'BN-VTC-2601A',
        expiryDate: inDays(610),
        quantity: 1200,
        costPerBaseUnit: 18,
        supplier: 'sup-abc',
        receivedDate: inDays(-90),
        isRecalled: false,
      },
    ],
    commonUse: 'Prevention and treatment of scurvy; general antioxidant support.',
    storage: 'Store below 25°C, protected from light.',
    prescriptionStatus: 'OTC',
    warnings: [],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-07-1120',
    manufacturer: 'Bulk Health Nigeria',
    averageDailySales: 1,
  },
  {
    id: 'med-suspected-recall',
    barcode: '8901030999888',
    name: 'Diazepam Tablets',
    genericName: 'Diazepam',
    strength: '10mg',
    dosageForm: 'Tablet',
    category: 'Psychotropic',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 380 },
      { key: 'strip', name: 'Strip (10)', multiplier: 10, sellingPrice: 3600 },
    ],
    totalQuantity: 40,
    lowStockThreshold: 30,
    expiryDate: inDays(340),
    supplier: 'sup-medplus',
    purchaseDate: inDays(-80),
    costPerBaseUnit: 150,
    pricePerBaseUnit: 380,
    batches: [
      {
        id: 'bat-dia-1',
        batchNumber: 'BN-DIA-2512X',
        expiryDate: inDays(340),
        quantity: 40,
        costPerBaseUnit: 150,
        supplier: 'sup-medplus',
        receivedDate: inDays(-80),
        // Recalled by the manufacturer. This batch must not sell even though
        // the product as a whole is not locked.
        isRecalled: true,
        recallReason: 'Manufacturer recall — wrong tablet marking reported.',
      },
    ],
    commonUse: 'Anxiety and short-term insomnia.',
    storage: 'Store below 25°C, protected from light.',
    prescriptionStatus: 'Controlled',
    warnings: [
      'Schedule IV — record the prescriber on every sale.',
      'Can cause drowsiness and dependence.',
    ],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-04-9001',
    manufacturer: 'Neon Pharmaceuticals',
    averageDailySales: 1,
  },
  {
    id: 'med-quinine',
    barcode: '8901030555002',
    name: 'Quinine Tablets',
    genericName: 'Quinine Sulfate',
    strength: '300mg',
    dosageForm: 'Tablet',
    category: 'Antimalarial',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 120 },
      { key: 'strip', name: 'Strip (10)', multiplier: 10, sellingPrice: 1150 },
    ],
    totalQuantity: 140,
    lowStockThreshold: 60,
    expiryDate: inDays(200),
    supplier: 'sup-abc',
    purchaseDate: inDays(-50),
    costPerBaseUnit: 50,
    pricePerBaseUnit: 120,
    batches: [
      {
        id: 'bat-qui-1',
        batchNumber: 'BN-QUI-2603A',
        expiryDate: inDays(200),
        quantity: 140,
        costPerBaseUnit: 50,
        supplier: 'sup-abc',
        receivedDate: inDays(-50),
        isRecalled: false,
      },
    ],
    // Stock-level safety lock: still on the shelf, must not be sold.
    doNotSell: {
      active: true,
      reason: 'Pending NAFDAC re-verification after a counterfeit alert.',
      lockedBy: 'Khadija Bello',
      lockedAt: hoursAgo(52),
    },
    commonUse: 'Malaria treatment where ACT is unavailable.',
    storage: 'Store below 25°C, protected from light.',
    prescriptionStatus: 'Prescription',
    warnings: ['Tinnitus and hearing loss at high doses.'],
    isBrand: false,
    nafdacRegNumber: 'NAFDAC-03-1145',
    manufacturer: 'J.P. Chehab Nigeria',
    averageDailySales: 5,
  },
  {
    id: 'med-ors',
    barcode: '8901030777018',
    name: 'ORS Sachets',
    genericName: 'Oral Rehydration Salts',
    strength: '20.5g',
    dosageForm: 'Sachet',
    category: 'First Aid',
    units: [
      { key: 'sachet', name: 'Sachet', multiplier: 1, sellingPrice: 200 },
      { key: 'pack', name: 'Pack (100)', multiplier: 100, sellingPrice: 19000 },
    ],
    totalQuantity: 900,
    lowStockThreshold: 200,
    expiryDate: inDays(700),
    supplier: 'sup-abc',
    purchaseDate: inDays(-15),
    costPerBaseUnit: 65,
    pricePerBaseUnit: 200,
    batches: [
      {
        id: 'bat-ors-1',
        batchNumber: 'BN-ORS-2607A',
        expiryDate: inDays(700),
        quantity: 900,
        costPerBaseUnit: 65,
        supplier: 'sup-abc',
        receivedDate: inDays(-15),
        isRecalled: false,
      },
    ],
    commonUse: 'Rehydration for diarrhoea, vomiting and heat exhaustion.',
    storage: 'Store in a cool dry place. Use within 24 hours of dissolving.',
    prescriptionStatus: 'OTC',
    warnings: ['Dissolve in exactly 1 litre of clean water.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-06-2210',
    manufacturer: 'Bayer Consumer Care',
    averageDailySales: 30,
  },
  {
    id: 'med-loratadine',
    barcode: '8901030888022',
    name: 'Loratadine Tablets',
    genericName: 'Loratadine',
    strength: '10mg',
    dosageForm: 'Tablet',
    category: 'Antihistamine',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 110 },
      { key: 'strip', name: 'Strip (10)', multiplier: 10, sellingPrice: 1050 },
    ],
    totalQuantity: 310,
    lowStockThreshold: 100,
    // Expiring within the warning window, and a decent amount of value.
    expiryDate: inDays(EXPIRY_WARNING_DAYS - 5),
    supplier: 'sup-abc',
    purchaseDate: inDays(-100),
    costPerBaseUnit: 40,
    pricePerBaseUnit: 110,
    batches: [
      {
        id: 'bat-lor-1',
        batchNumber: 'BN-LOR-2509A',
        expiryDate: inDays(EXPIRY_WARNING_DAYS - 5),
        quantity: 310,
        costPerBaseUnit: 40,
        supplier: 'sup-abc',
        receivedDate: inDays(-100),
        isRecalled: false,
      },
    ],
    commonUse: 'Hay fever, hives and other allergic symptoms.',
    storage: 'Store below 25°C in a dry place.',
    prescriptionStatus: 'OTC',
    warnings: ['May cause drowsiness in some people.'],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-02-7781',
    manufacturer: 'Greenfield Pharmaceuticals',
    averageDailySales: 12,
  },
  {
    id: 'med-folic',
    barcode: '8901030333004',
    name: 'Folic Acid Tablets',
    genericName: 'Folic Acid',
    strength: '5mg',
    dosageForm: 'Tablet',
    category: 'Supplement',
    units: [
      { key: 'tablet', name: 'Tablet', multiplier: 1, sellingPrice: 90 },
      { key: 'strip', name: 'Strip (30)', multiplier: 30, sellingPrice: 2600 },
    ],
    totalQuantity: 180,
    lowStockThreshold: 90,
    expiryDate: inDays(480),
    supplier: 'sup-medplus',
    purchaseDate: inDays(-35),
    costPerBaseUnit: 30,
    pricePerBaseUnit: 90,
    batches: [
      {
        id: 'bat-fol-1',
        batchNumber: 'BN-FOL-2605A',
        expiryDate: inDays(480),
        quantity: 180,
        costPerBaseUnit: 30,
        supplier: 'sup-medplus',
        receivedDate: inDays(-35),
        isRecalled: false,
      },
    ],
    commonUse: 'Anaemia prevention and prenatal supplementation.',
    storage: 'Store below 25°C, protected from light.',
    prescriptionStatus: 'OTC',
    warnings: [],
    isBrand: false,
    doNotSell: { active: false },
    nafdacRegNumber: 'NAFDAC-07-4420',
    manufacturer: 'Bulk Health Nigeria',
    averageDailySales: 7,
  },
];

/* -------------------------------------------------------------- suppliers */

export const SEED_SUPPLIERS: AppState['suppliers'] = [
  {
    id: 'sup-abc',
    name: 'ABC Pharmacy Supplies',
    contactPerson: 'Chidi Okeke',
    phone: '+2348021112233',
    address: '14 Balogun Street, Lagos Island, Lagos',
    leadTimeDays: 3,
    rating: 4.6,
  },
  {
    id: 'sup-medplus',
    name: 'MedPlus Distributors',
    contactPerson: 'Fatima Sani',
    phone: '+2348034445566',
    address: '22 Awolowo Road, Ikoyi, Lagos',
    leadTimeDays: 5,
    rating: 4.2,
  },
];

/* ------------------------------------------------------------------ people */

export const SEED_CUSTOMERS: AppState['customers'] = [
  {
    id: 'cus-001',
    code: 'CUST-1001',
    name: 'Grace Adeyemi',
    phone: '08021112233',
    email: 'grace.adeyemi@example.com',
    walletBalance: money(12500),
    outstandingDebt: money(8400),
    totalSpent: money(412_500),
    purchaseCount: 34,
    registeredDate: inDays(-420),
    lastPurchaseDate: inDays(-6),
    consentForReminders: true,
    chronicMedications: ['med-amoxicillin', 'med-metronidazole'],
    notes: 'Hypertension patient. Prefers generics.',
  },
  {
    id: 'cus-002',
    code: 'CUST-1002',
    name: 'Ibrahim Musa',
    phone: '08057778899',
    walletBalance: money(0),
    outstandingDebt: money(0),
    totalSpent: money(96_800),
    purchaseCount: 11,
    registeredDate: inDays(-180),
    lastPurchaseDate: inDays(-22),
    consentForReminders: false,
    chronicMedications: ['med-tramadol'],
  },
  {
    id: 'cus-003',
    code: 'CUST-1003',
    name: 'Blessing Eze',
    phone: '07033445566',
    walletBalance: money(3200),
    outstandingDebt: money(15_600),
    totalSpent: money(228_400),
    purchaseCount: 27,
    registeredDate: inDays(-300),
    lastPurchaseDate: inDays(-2),
    consentForReminders: true,
    chronicMedications: ['med-loratadine'],
    notes: 'Runs a small clinic. Often buys on credit, settles monthly.',
  },
];

export const SEED_CREDIT_ACCOUNTS: AppState['creditAccounts'] = [
  {
    id: 'cred-001',
    name: 'St. Jude Academy',
    type: 'school' as const,
    contactPerson: 'Mr. Emeka Nwosu',
    phone: '+2348035566778',
    creditLimit: money(500_000),
    outstandingBalance: money(128_400),
    status: 'active' as const,
    createdAt: inDays(-300),
    ledger: [
      {
        id: 'led-001',
        date: inDays(-12),
        type: 'charge' as const,
        amount: money(42_000),
        balanceAfter: money(128_400),
        note: 'Monthly supply — clinic supplies',
      },
      {
        id: 'led-002',
        date: inDays(-40),
        type: 'payment' as const,
        amount: money(100_000),
        balanceAfter: money(86_400),
        note: 'Part payment by transfer',
      },
    ],
  },
  {
    id: 'cred-002',
    name: 'Bright Horizon Clinic',
    type: 'clinic' as const,
    contactPerson: 'Dr. Amaka Obi',
    phone: '+2348027766554',
    creditLimit: money(300_000),
    outstandingBalance: money(311_200),
    status: 'active' as const,
    createdAt: inDays(-210),
    ledger: [
      {
        id: 'led-003',
        date: inDays(-5),
        type: 'charge' as const,
        amount: money(18_900),
        balanceAfter: money(311_200),
        note: 'Emergency supply — weekend',
      },
    ],
  },
];

/* ------------------------------------------------------------------ sales */

/** Recent sales so the dashboard has real numbers to show. */
export const SEED_SALES: AppState['sales'] = [
  {
    id: 'sale-001',
    receiptNumber: 'PF-2026-0001',
    date: hoursAgo(3),
    attendantId: assistant.id,
    attendantName: assistant.name,
    items: [
      {
        medicineId: 'med-paracetamol',
        medicineName: 'Paracetamol Tablets',
        genericName: 'Paracetamol',
        unitKey: 'card',
        unitName: 'Card (10)',
        unitMultiplier: 10,
        unitPrice: 2000,
        quantity: 2,
        baseUnitsTotal: 20,
        lineTotal: money(4000),
        costPerBaseUnitSnapshot: 100,
      },
      {
        medicineId: 'med-coartem',
        medicineName: 'Coartem Tablets',
        genericName: 'Artemether / Lumefantrine',
        unitKey: 'course',
        unitName: 'Course (6)',
        unitMultiplier: 6,
        unitPrice: 2700,
        quantity: 1,
        baseUnitsTotal: 6,
        lineTotal: money(2700),
        costPerBaseUnitSnapshot: 260,
      },
    ],
    subtotal: money(6700),
    discount: money(200),
    discountReason: 'Staff discount',
    total: money(6500),
    paymentMethod: 'cash' as const,
    status: 'paid' as const,
    amountPaid: money(6500),
    outstandingBalance: money(0),
  },
  {
    id: 'sale-002',
    receiptNumber: 'PF-2026-0002',
    date: hoursAgo(26),
    attendantId: assistant.id,
    attendantName: assistant.name,
    items: [
      {
        medicineId: 'med-amoxicillin',
        medicineName: 'Amoxicillin Capsules',
        genericName: 'Amoxicillin',
        unitKey: 'pack',
        unitName: 'Pack (21)',
        unitMultiplier: 21,
        unitPrice: 7000,
        quantity: 1,
        baseUnitsTotal: 21,
        lineTotal: money(7000),
        costPerBaseUnitSnapshot: 160,
      },
    ],
    subtotal: money(7000),
    discount: money(0),
    total: money(7000),
    paymentMethod: 'transfer' as const,
    status: 'credit' as const,
    amountPaid: money(2000),
    outstandingBalance: money(5000),
    customerId: 'cus-003',
    customerName: 'Blessing Eze',
    customerPhone: '07033445566',
    dispensedAgainstPrescription: true,
  },
  {
    id: 'sale-003',
    receiptNumber: 'PF-2026-0003',
    date: hoursAgo(50),
    attendantId: owner.id,
    attendantName: owner.name,
    items: [
      {
        medicineId: 'med-tramadol',
        medicineName: 'Tramadol Capsules',
        genericName: 'Tramadol HCl',
        unitKey: 'strip',
        unitName: 'Strip (10)',
        unitMultiplier: 10,
        unitPrice: 4600,
        quantity: 1,
        baseUnitsTotal: 10,
        lineTotal: money(4600),
        costPerBaseUnitSnapshot: 210,
      },
    ],
    subtotal: money(4600),
    discount: money(0),
    total: money(4600),
    paymentMethod: 'pos_card' as const,
    status: 'paid' as const,
    amountPaid: money(4600),
    outstandingBalance: money(0),
    dispensedAgainstPrescription: true,
  },
  {
    id: 'sale-004',
    receiptNumber: 'PF-2026-0004',
    date: hoursAgo(74),
    attendantId: assistant.id,
    attendantName: assistant.name,
    items: [
      {
        medicineId: 'med-ors',
        medicineName: 'ORS Sachets',
        genericName: 'Oral Rehydration Salts',
        unitKey: 'pack',
        unitName: 'Pack (100)',
        unitMultiplier: 100,
        unitPrice: 19000,
        quantity: 1,
        baseUnitsTotal: 100,
        lineTotal: money(19_000),
        costPerBaseUnitSnapshot: 65,
      },
      {
        medicineId: 'med-metronidazole',
        medicineName: 'Metronidazole Tablets',
        genericName: 'Metronidazole',
        unitKey: 'strip',
        unitName: 'Strip (10)',
        unitMultiplier: 10,
        unitPrice: 1350,
        quantity: 2,
        baseUnitsTotal: 20,
        lineTotal: money(2700),
        costPerBaseUnitSnapshot: 45,
      },
    ],
    subtotal: money(21_700),
    discount: money(0),
    total: money(21_700),
    paymentMethod: 'cash' as const,
    status: 'part_paid' as const,
    amountPaid: money(15_000),
    outstandingBalance: money(6700),
    customerId: 'cus-001',
    customerName: 'Grace Adeyemi',
    customerPhone: '08021112233',
  },
];

/* --------------------------------------------------- receipts and requests */

export const SEED_STOCK_RECEIPTS: AppState['stockReceipts'] = [
  {
    id: 'rcp-001',
    receiptNumber: 'GRN-2026-0118',
    medicineId: 'med-amoxicillin',
    medicineName: 'Amoxicillin Capsules',
    batchNumber: 'BN-AMP-2609B',
    baseUnitsReceived: 200,
    supplier: 'sup-medplus',
    expiryDate: inDays(360),
    dateReceived: hoursAgo(20),
    receivedBy: assistant.name,
    receivedByRole: 'assistant' as const,
    // Awaiting owner pricing — this is what drives the pending-pricing queue.
    status: 'pending_pricing' as const,
  },
  {
    id: 'rcp-002',
    receiptNumber: 'GRN-2026-0117',
    medicineId: 'med-ors',
    medicineName: 'ORS Sachets',
    batchNumber: 'BN-ORS-2607A',
    baseUnitsReceived: 900,
    supplier: 'sup-abc',
    expiryDate: inDays(700),
    dateReceived: hoursAgo(30),
    receivedBy: owner.name,
    receivedByRole: 'owner' as const,
    status: 'confirmed' as const,
    costPerBaseUnit: 65,
    pricePerBaseUnit: 200,
    pricedBy: owner.name,
    pricedAt: hoursAgo(28),
  },
];

export const SEED_MEDICINE_REQUESTS: AppState['medicineRequests'] = [
  {
    id: 'req-001',
    medicineName: 'Ciprofloxacin Tablets',
    genericName: 'Ciprofloxacin',
    customerName: 'Dr. Amaka Obi',
    customerPhone: '+2348027766554',
    quantityRequested: 200,
    urgency: 'urgent' as const,
    status: 'pending_restock' as const,
    recordedAt: hoursAgo(9),
  },
  {
    id: 'req-002',
    medicineName: 'Loratadine Tablets',
    customerName: 'Blessing Eze',
    customerPhone: '07033445566',
    quantityRequested: 100,
    urgency: 'routine' as const,
    status: 'pending_restock' as const,
    recordedAt: hoursAgo(31),
  },
];

/* ------------------------------------------------------------------ orders */

export const SEED_CUSTOMER_ORDERS: AppState['customerOrders'] = [
  {
    id: 'ord-001',
    orderNumber: 'ORD-PF-9241',
    customerId: 'cus-001',
    customerName: 'Grace Adeyemi',
    customerPhone: '08021112233',
    deliveryType: 'delivery' as const,
    deliveryAddress: '12 Bourdillon Road, Ikoyi, Lagos',
    branchName: 'Ojota Branch',
    items: [
      {
        medicineId: 'med-amoxicillin',
        medicineName: 'Amoxicillin Capsules',
        unitName: 'Pack (21)',
        quantity: 2,
        lineTotal: money(14_000),
      },
    ],
    subtotal: money(14_000),
    deliveryFee: money(1000),
    total: money(15_000),
    paymentMethod: 'pay_on_delivery' as const,
    paymentStatus: 'pending' as const,
    orderStatus: 'pending_review' as const,
    prescriptionUploaded: true,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'ord-002',
    orderNumber: 'ORD-PF-9240',
    customerId: 'cus-003',
    customerName: 'Blessing Eze',
    customerPhone: '07033445566',
    deliveryType: 'pickup' as const,
    branchName: 'Ojota Branch',
    items: [
      {
        medicineId: 'med-loratadine',
        medicineName: 'Loratadine Tablets',
        unitName: 'Strip (10)',
        quantity: 3,
        lineTotal: money(3150),
      },
      {
        medicineId: 'med-folic',
        medicineName: 'Folic Acid Tablets',
        unitName: 'Strip (30)',
        quantity: 1,
        lineTotal: money(2600),
      },
    ],
    subtotal: money(5750),
    deliveryFee: money(0),
    total: money(5750),
    paymentMethod: 'bank_transfer' as const,
    paymentStatus: 'paid' as const,
    orderStatus: 'ready_for_pickup' as const,
    prescriptionUploaded: false,
    createdAt: hoursAgo(38),
    updatedAt: hoursAgo(20),
  },
];

/* ------------------------------------------------------------ notifications */

export const SEED_NOTIFICATIONS: AppState['notifications'] = [
  {
    id: 'ntf-001',
    type: 'pending_pricing' as const,
    title: 'Receipt awaiting pricing',
    message: 'GRN-2026-0118 · Amoxicillin Capsules · 200 units',
    date: hoursAgo(20),
    read: false,
    severity: 'warning' as const,
    to: '/pricing',
  },
  {
    id: 'ntf-002',
    type: 'low_stock' as const,
    title: 'Ciprofloxacin out of stock',
    message: 'Selling 8 a day. 13 requests logged this week.',
    date: hoursAgo(9),
    read: false,
    severity: 'urgent' as const,
    to: '/inventory',
  },
  {
    id: 'ntf-003',
    type: 'expiry_risk' as const,
    title: '2 products expiring soon',
    message: 'Omeprazole and Loratadine both inside 90 days.',
    date: hoursAgo(30),
    read: false,
    severity: 'warning' as const,
    to: '/expiry',
  },
  {
    id: 'ntf-004',
    type: 'medicine_request' as const,
    title: 'Customer request — Ciprofloxacin',
    message: 'Dr. Amaka Obi asked for 200 units.',
    date: hoursAgo(9),
    read: true,
    severity: 'info' as const,
    to: '/customers',
  },
  {
    id: 'ntf-005',
    type: 'cost_increase' as const,
    title: 'Cough Syrup margin under 20%',
    message: 'Cost rose to ₦2,050. Current margin is 15%.',
    date: hoursAgo(52),
    read: true,
    severity: 'info' as const,
    to: '/pricing',
  },
];

export const SEED_BRANCH: AppState['branch'] = {
  id: 'br-ojota',
  name: 'Ojota Branch',
  address: '88 Awolowo Way, Ojota, Lagos',
  city: 'Lagos',
  state: 'Lagos',
  phone: '+2348012345678',
  openingHours: '8:00 – 22:00 daily',
  isOpenNow: true,
  rating: 4.7,
  reviewsCount: 212,
  isMainHub: true,
};

/* ------------------------------------------------------------ audit events */

export const SEED_AUDIT_EVENTS: AppState['auditEvents'] = [
  {
    id: 'aud-001',
    timestamp: hoursAgo(3),
    actorName: assistant.name,
    actorRole: 'assistant' as const,
    action: 'sale' as const,
    description: 'Completed sale PF-2026-0001 for ₦6,500',
    metadata: { receiptNumber: 'PF-2026-0001' },
  },
  {
    id: 'aud-002',
    timestamp: hoursAgo(9),
    actorName: assistant.name,
    actorRole: 'assistant' as const,
    action: 'stock_receipt' as const,
    description: 'Received GRN-2026-0118 · Amoxicillin · 200 units',
    metadata: { receiptId: 'rcp-001' },
  },
  {
    id: 'aud-003',
    timestamp: hoursAgo(52),
    actorName: owner.name,
    actorRole: 'owner' as const,
    action: 'recall_lock' as const,
    description: 'Locked Quinine Tablets — NAFDAC re-verification',
    metadata: { medicineId: 'med-quinine' },
  },
  {
    id: 'aud-004',
    timestamp: hoursAgo(74),
    actorName: assistant.name,
    actorRole: 'assistant' as const,
    action: 'discount' as const,
    description: 'Applied ₦200 staff discount on PF-2026-0001',
  },
];

/* ---------------------------------------------------------------- the state */

export function createSeedState(): AppState {
  return {
    currentUser: owner,
    users: [...SEED_USERS],
    medicines: SEED_MEDICINES.map((m) => ({ ...m })),
    suppliers: SEED_SUPPLIERS.map((s) => ({ ...s })),
    creditAccounts: SEED_CREDIT_ACCOUNTS.map((a) => ({
      ...a,
      ledger: a.ledger.map((l) => ({ ...l })),
    })),
    customers: SEED_CUSTOMERS.map((c) => ({ ...c })),
    sales: SEED_SALES.map((s) => ({
      ...s,
      items: s.items.map((i) => ({ ...i })),
    })),
    stockReceipts: SEED_STOCK_RECEIPTS.map((r) => ({ ...r })),
    auditEvents: SEED_AUDIT_EVENTS.map((e) => ({ ...e })),
    notifications: SEED_NOTIFICATIONS.map((n) => ({ ...n })),
    customerOrders: SEED_CUSTOMER_ORDERS.map((o) => ({
      ...o,
      items: o.items.map((i) => ({ ...i })),
    })),
    medicineRequests: SEED_MEDICINE_REQUESTS.map((r) => ({ ...r })),
    branch: { ...SEED_BRANCH },
    stockMovements: [],
  };
}
